/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-3ea28912",
        "v-3bf829c2"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-d16809ac",
        "v-4fdadb04",
        "v-7760dbfe"
      ]
    },
    "Array": {
      "key": "Array",
      "scope": "tags",
      "path": "/tag/Array/",
      "pageKeys": [
        "v-71aabf32"
      ]
    },
    "Object": {
      "key": "Object",
      "scope": "tags",
      "path": "/tag/Object/",
      "pageKeys": [
        "v-9ae5d6c0"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-4f6a39b2"
      ]
    },
    "继承": {
      "key": "继承",
      "scope": "tags",
      "path": "/tag/继承/",
      "pageKeys": [
        "v-d33e359c",
        "v-f3250d28"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-120f1c5c"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-2e48bc4e"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-24548be8"
      ]
    },
    "八股文": {
      "key": "八股文",
      "scope": "tags",
      "path": "/tag/八股文/",
      "pageKeys": [
        "v-13919e72",
        "v-86976a5c",
        "v-242c4a02"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-fa48e2e6"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-b993f2a8"
      ]
    },
    "扁平化": {
      "key": "扁平化",
      "scope": "tags",
      "path": "/tag/扁平化/",
      "pageKeys": [
        "v-1076d512"
      ]
    },
    "发布订阅": {
      "key": "发布订阅",
      "scope": "tags",
      "path": "/tag/发布订阅/",
      "pageKeys": [
        "v-9b10f19c"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "tags",
      "path": "/tag/面试题/",
      "pageKeys": [
        "v-a7e0981c"
      ]
    }
  },
  "categories": {
    "Byte": {
      "key": "Byte",
      "scope": "categories",
      "path": "/categories/Byte/",
      "pageKeys": [
        "v-3ea28912",
        "v-71aabf32",
        "v-3bf829c2",
        "v-9ae5d6c0"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-d16809ac",
        "v-4fdadb04",
        "v-7760dbfe"
      ]
    },
    "Node": {
      "key": "Node",
      "scope": "categories",
      "path": "/categories/Node/",
      "pageKeys": [
        "v-4f6a39b2"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-d33e359c",
        "v-120f1c5c",
        "v-2e48bc4e",
        "v-f3250d28",
        "v-24548be8",
        "v-13919e72",
        "v-86976a5c",
        "v-242c4a02"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-fa48e2e6",
        "v-b993f2a8"
      ]
    },
    "andition": {
      "key": "andition",
      "scope": "categories",
      "path": "/categories/andition/",
      "pageKeys": [
        "v-1076d512",
        "v-9b10f19c",
        "v-a7e0981c"
      ]
    }
  },
  "timeline": {}
}